version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    env_file: env.template
    volumes:
      - .:/go/src/github/octopusx/linode-backup
    working_dir: /go/src/github/octopusx/linode-backup
    command: "go run ."
